exclude: |
  (?x)(
    ^archive/|
    ^config/|
    ^docs/|
    ^docsource/
  )

repos:

  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: 'https://github.com/kynan/nbstripout'
    rev: 0.5.0
    hooks:
      - id: nbstripout

  - repo: 'https://github.com/psf/black'
    rev: 22.3.0
    hooks:
      - id: black
      - id: black-jupyter

  - repo: 'https://github.com/pycqa/flake8'
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: automation_sb/archive/
        args: [
            '--ignore=E203, W503, F401, E265, W605', # https://lintlyci.github.io/Flake8Rules/ , E266, E402, E501, E722 , W503, F401, F403
            '--max-line-length=88',
#            '--max-complexity=18',
#            '--select=B, C, E, F, W, T4, B9'
        ]
